<?php

namespace Phiki\Theme;

abstract class DefaultThemes
{
    final const NAMES_TO_PATHS = ["one-dark-pro" => __DIR__ . "/../../resources/themes/one-dark-pro.json",
"solarized-light" => __DIR__ . "/../../resources/themes/solarized-light.json",
"vitesse-black" => __DIR__ . "/../../resources/themes/vitesse-black.json",
"github-light-default" => __DIR__ . "/../../resources/themes/github-light-default.json",
"slack-dark" => __DIR__ . "/../../resources/themes/slack-dark.json",
"everforest-dark" => __DIR__ . "/../../resources/themes/everforest-dark.json",
"rose-pine-moon" => __DIR__ . "/../../resources/themes/rose-pine-moon.json",
"everforest-light" => __DIR__ . "/../../resources/themes/everforest-light.json",
"laserwave" => __DIR__ . "/../../resources/themes/laserwave.json",
"github-light-high-contrast" => __DIR__ . "/../../resources/themes/github-light-high-contrast.json",
"catppuccin-mocha" => __DIR__ . "/../../resources/themes/catppuccin-mocha.json",
"red" => __DIR__ . "/../../resources/themes/red.json",
"material-theme-lighter" => __DIR__ . "/../../resources/themes/material-theme-lighter.json",
"one-light" => __DIR__ . "/../../resources/themes/one-light.json",
"aurora-x" => __DIR__ . "/../../resources/themes/aurora-x.json",
"tokyo-night" => __DIR__ . "/../../resources/themes/tokyo-night.json",
"catppuccin-macchiato" => __DIR__ . "/../../resources/themes/catppuccin-macchiato.json",
"github-dark" => __DIR__ . "/../../resources/themes/github-dark.json",
"rose-pine-dawn" => __DIR__ . "/../../resources/themes/rose-pine-dawn.json",
"poimandres" => __DIR__ . "/../../resources/themes/poimandres.json",
"github-dark-high-contrast" => __DIR__ . "/../../resources/themes/github-dark-high-contrast.json",
"material-theme" => __DIR__ . "/../../resources/themes/material-theme.json",
"dracula" => __DIR__ . "/../../resources/themes/dracula.json",
"github-dark-default" => __DIR__ . "/../../resources/themes/github-dark-default.json",
"github-dark-dimmed" => __DIR__ . "/../../resources/themes/github-dark-dimmed.json",
"rose-pine" => __DIR__ . "/../../resources/themes/rose-pine.json",
"kanagawa-lotus" => __DIR__ . "/../../resources/themes/kanagawa-lotus.json",
"kanagawa-dragon" => __DIR__ . "/../../resources/themes/kanagawa-dragon.json",
"dark-plus" => __DIR__ . "/../../resources/themes/dark-plus.json",
"ayu-dark" => __DIR__ . "/../../resources/themes/ayu-dark.json",
"min-dark" => __DIR__ . "/../../resources/themes/min-dark.json",
"monokai" => __DIR__ . "/../../resources/themes/monokai.json",
"nord" => __DIR__ . "/../../resources/themes/nord.json",
"catppuccin-frappe" => __DIR__ . "/../../resources/themes/catppuccin-frappe.json",
"github-light" => __DIR__ . "/../../resources/themes/github-light.json",
"dracula-soft" => __DIR__ . "/../../resources/themes/dracula-soft.json",
"synthwave-84" => __DIR__ . "/../../resources/themes/synthwave-84.json",
"vitesse-dark" => __DIR__ . "/../../resources/themes/vitesse-dark.json",
"andromeeda" => __DIR__ . "/../../resources/themes/andromeeda.json",
"light-plus" => __DIR__ . "/../../resources/themes/light-plus.json",
"slack-ochin" => __DIR__ . "/../../resources/themes/slack-ochin.json",
"solarized-dark" => __DIR__ . "/../../resources/themes/solarized-dark.json",
"material-theme-ocean" => __DIR__ . "/../../resources/themes/material-theme-ocean.json",
"vitesse-light" => __DIR__ . "/../../resources/themes/vitesse-light.json",
"vesper" => __DIR__ . "/../../resources/themes/vesper.json",
"kanagawa-wave" => __DIR__ . "/../../resources/themes/kanagawa-wave.json",
"plastic" => __DIR__ . "/../../resources/themes/plastic.json",
"material-theme-darker" => __DIR__ . "/../../resources/themes/material-theme-darker.json",
"night-owl" => __DIR__ . "/../../resources/themes/night-owl.json",
"catppuccin-latte" => __DIR__ . "/../../resources/themes/catppuccin-latte.json",
"min-light" => __DIR__ . "/../../resources/themes/min-light.json",
"snazzy-light" => __DIR__ . "/../../resources/themes/snazzy-light.json",
"houston" => __DIR__ . "/../../resources/themes/houston.json",
"material-theme-palenight" => __DIR__ . "/../../resources/themes/material-theme-palenight.json"];
}